#!/usr/bin/env node
// Pulls compiled ABIs from packages/contracts/artifacts and emits a typed
// index.ts that apps/web + apps/api import. Run after `hardhat compile`.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { resolve, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ARTIFACTS = resolve(__dirname, "../../contracts/artifacts/contracts");
const OUT_FILE = resolve(__dirname, "../src/index.ts");

const TARGETS = [
  ["YieldVault", "core/YieldVault.sol/YieldVault.json"],
  ["Paymaster", "core/Paymaster.sol/Paymaster.json"],
  ["YieldPilotAccount", "core/YieldPilotAccount.sol/YieldPilotAccount.json"],
  ["YieldPilotAccountFactory", "core/YieldPilotAccountFactory.sol/YieldPilotAccountFactory.json"],
  ["MockUsdc", "mocks/MockUSDC.sol/MockUSDC.json"],
  ["MockAave", "mocks/MockAave.sol/MockAave.json"],
];

if (!existsSync(ARTIFACTS)) {
  console.warn(`[extract-abis] No artifacts yet at ${ARTIFACTS} — run \`pnpm compile\` first. Skipping.`);
  process.exit(0);
}

const lines = ["// AUTO-GENERATED by scripts/extract-abis.mjs — do not edit.", ""];

for (const [name, path] of TARGETS) {
  const full = join(ARTIFACTS, path);
  if (!existsSync(full)) {
    console.warn(`[extract-abis] missing ${path} — skipping ${name}`);
    lines.push(`export const ${name}Abi = [] as const;`);
    continue;
  }
  const artifact = JSON.parse(readFileSync(full, "utf8"));
  lines.push(`export const ${name}Abi = ${JSON.stringify(artifact.abi)} as const;`);
}

mkdirSync(dirname(OUT_FILE), { recursive: true });
writeFileSync(OUT_FILE, lines.join("\n") + "\n");
console.log(`[extract-abis] wrote ${OUT_FILE}`);
